### ISSUE TITLE
Installation crash when attempting to update "testthat" package

### ISSUE THREAD

**Issue by taylor-curley** [JackEdTaylor/LexOPS#2]
Installation on R 4.0.2 will crash when attempting to update the `testthat` package. 

Work around: Skip package updates upon installation by choosing option 3 - "no updates". Update `testthat` outside of installation.

**Comment by JackEdTaylor** [comment]
I think this problem comes from `devtools` depending on `testthat`. LexOPS suggests `testthat` to make `R CMD check` happy.

Since it's outside of LexOPS I'm going to close this issue.
