### ISSUE TITLE
Non-Stimulus Splits with Short Lists 

### ISSUE THREAD

**Issue by xalario** [JackEdTaylor/LexOPS#4]
Hi,

I am so happy to have found this package, thank you very much!

My question is about the generation of "non-stimulus splits" using a (relatively) short list of materials. 

`generate()` is not converging even with very relaxed constraints. I wonder whether I am doing something wrong. The details are pasted below.

Thank you in advance for your help

Xavier

I have a file `dxE` that may have between 30 and 70 `Item` (say N = 32 in the example below). 

I want to split it into two groups matched for their `frequency`. The range of `frequency` values is fairly limited `0.07 - 6.96`. 

I most often get the message:

> *n is too large; requested n of 16, but the condition with the fewest members has 13 entries. Ensure n < 13. Will generate as many stimuli as possible.*

This is the case even when I use very broad constraints in `control_for()`, that I expect to not constrain the matching. Why is it that "n is too large"?

 
**Sample code**

```
set.seed(13331)
d = tibble(Item = 1:32, frequency = runif(32, min = .07, max = 6.96) )
           
d %>%
    set_options(id_col = "Item") %>%
    split_random(2) %>%
    control_for(frequency, -100:100) %>%
    LexOPS::generate(n=32/2) ->
    foo
```

**Comment by JackEdTaylor** [comment]
Hi @xalario 

Thanks for the example! This is because of how LexOPS currently deals with random splits. Using `split_random(2)` is equivalent to:

```r
d %>%
  mutate(x = sample(c("a", "b"), size=nrow(.), replace=TRUE)) %>%
  set_options(id_col = "Item") %>%
  split_by(x, "a" ~ "b") %>%
  control_for(frequency, -100:100) %>%
  LexOPS::generate(n=32/2)
```

So the problem is that LexOPS is splitting the dataset randomly, but not necessarily into equally sized groups. In your example, the smallest group has 11 entries. A solution could be to specify that there should be as close to equal numbers of each group as possible, with the over-represented category selected randomly.

```r
d %>%
  mutate(x = sample(rep(sample(c("a", "b")), length.out=nrow(.)))) %>%
  set_options(id_col = "Item") %>%
  split_by(x, "a" ~ "b") %>%
  control_for(frequency, -100:100) %>%
  LexOPS::generate(n=32/2)
```

I think an argument to `split_random()` that results in this behaviour would be useful so will put it on my to-do list. Till then, creating `x` manually (as above) will work.

**Comment by JackEdTaylor** [comment]
The dev version - `devtools::install_github("JackEdTaylor/LexOPS")` - now has `equal_size` argument for `split_random()`:

```r
set.seed(13331)
d = tibble(Item = 1:32, frequency = runif(32, min = .07, max = 6.96) )

d %>%
  set_options(id_col = "Item") %>%
  split_random(2, equal_size=TRUE) %>%
  control_for(frequency, -100:100) %>%
  LexOPS::generate(n=32/2)
```

Default is `FALSE` to avoid breaking old code.

**Comment by xalario** [comment]
Thanks a lot! 

I have used the first suggestion successfully, and embedded it in a `while` loop that stops only if enough lines are generated.

When loading the dev version I get errors, but I suspect that is another issue.

PS a quotation mark is missing in your parenthesis after `LexOPS`

**Comment by JackEdTaylor** [comment]
Not sure what the installation problem might be - do open another issue if you think it might be a problem with the package!

Thanks again
